language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
env:
  - DJANGO=2.1.3 
cache: 
  - pip3
install:
  - pip3 install -r requirements.txt
script:
  - python3 manage.py